global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
  - job_name: 'app'
    static_configs:
      - targets: ['app1:8000', 'app2:8000']