name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Рабочая ветка для деплоя
  pull_request:
    branches:
      - main  # Для тестирования перед слиянием в основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout кода
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Настройка Python и зависимостей
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Укажите нужную версию Python

      # 3. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Запуск юнит-тестов
      - name: Run tests
        run: |
          python manage.py test  # Ваши тесты

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Этот шаг будет выполнен только после завершения шага build
    if: github.ref == 'refs/heads/main'  # Деплой только для ветки main

    steps:
      # 1. Checkout кода
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Деплой на staging
      - name: Deploy to Staging
        run: |
          # Здесь вы можете настроить деплой на staging-сервер
          ssh user@staging-server "cd /path/to/project && git pull && docker-compose up -d"

      # 3. Деплой на production
      - name: Deploy to Production
        run: |
          # Деплой на продакшн
          ssh user@production-server "cd /path/to/project && git pull && docker-compose up -d"
